name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Information
        run: ./gradlew project tasks dependencies

  test:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 30
    name: Test Project
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean test

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            prefix: ./
          - os: windows-latest
            prefix: .\
          - os: macos-latest
            prefix: ./

    name: Create Artifacts / ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        if: matrix.os != 'windows-latest'
        run: chmod +x ./gradlew
      - name: Build Project
        run: ${{ matrix.prefix }}gradlew clean build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kotatime-${{ matrix.os }}
          path: build/distributions/*.zip