name: Release Artifacts
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    needs: test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            prefix: ./
          - os: windows-latest
            prefix: .\
          - os: macos-latest
            prefix: ./

    name: Create Artifacts
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change Permissions
        if: matrix.os != 'windows-latest'
        run: chmod +x ./gradlew
      - name: Build Project
        run: ${{ matrix.prefix }}gradlew clean build
      - name: Upload Artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/release/*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true