name: Release Artifacts
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    needs: test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    name: Create Artifacts
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Build Project
        run: ./gradlew clean build
      - name: Upload Artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/distributions/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true